name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: luacheck/luacheck@v1
        continue-on-error: true
        with:
          args: lua
